// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: downloads.sql

package db

import (
	"context"
	"database/sql"
)

const createSkillDownload = `-- name: CreateSkillDownload :exec
INSERT INTO skill_downloads (
    skill_name,
    installed_as,
    skill_version,
    source_type,
    source_name,
    source_url,
    downloader,
    downloader_host,
    downloaded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillDownloadParams struct {
	SkillName      string         `json:"skill_name"`
	InstalledAs    string         `json:"installed_as"`
	SkillVersion   sql.NullString `json:"skill_version"`
	SourceType     string         `json:"source_type"`
	SourceName     sql.NullString `json:"source_name"`
	SourceUrl      sql.NullString `json:"source_url"`
	Downloader     string         `json:"downloader"`
	DownloaderHost sql.NullString `json:"downloader_host"`
	DownloadedAt   string         `json:"downloaded_at"`
}

func (q *Queries) CreateSkillDownload(ctx context.Context, arg CreateSkillDownloadParams) error {
	_, err := q.db.ExecContext(ctx, createSkillDownload,
		arg.SkillName,
		arg.InstalledAs,
		arg.SkillVersion,
		arg.SourceType,
		arg.SourceName,
		arg.SourceUrl,
		arg.Downloader,
		arg.DownloaderHost,
		arg.DownloadedAt,
	)
	return err
}

const listSkillDownloads = `-- name: ListSkillDownloads :many
SELECT id, skill_name, installed_as, skill_version, source_type, source_name, source_url, downloader, downloader_host, downloaded_at FROM skill_downloads
ORDER BY downloaded_at DESC, id DESC
`

func (q *Queries) ListSkillDownloads(ctx context.Context) ([]SkillDownload, error) {
	rows, err := q.db.QueryContext(ctx, listSkillDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillDownload
	for rows.Next() {
		var i SkillDownload
		if err := rows.Scan(
			&i.ID,
			&i.SkillName,
			&i.InstalledAs,
			&i.SkillVersion,
			&i.SourceType,
			&i.SourceName,
			&i.SourceUrl,
			&i.Downloader,
			&i.DownloaderHost,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillDownloadsBySkill = `-- name: ListSkillDownloadsBySkill :many
SELECT id, skill_name, installed_as, skill_version, source_type, source_name, source_url, downloader, downloader_host, downloaded_at FROM skill_downloads
WHERE skill_name = ? OR installed_as = ?
ORDER BY downloaded_at DESC, id DESC
`

type ListSkillDownloadsBySkillParams struct {
	SkillName   string `json:"skill_name"`
	InstalledAs string `json:"installed_as"`
}

func (q *Queries) ListSkillDownloadsBySkill(ctx context.Context, arg ListSkillDownloadsBySkillParams) ([]SkillDownload, error) {
	rows, err := q.db.QueryContext(ctx, listSkillDownloadsBySkill, arg.SkillName, arg.InstalledAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillDownload
	for rows.Next() {
		var i SkillDownload
		if err := rows.Scan(
			&i.ID,
			&i.SkillName,
			&i.InstalledAs,
			&i.SkillVersion,
			&i.SourceType,
			&i.SourceName,
			&i.SourceUrl,
			&i.Downloader,
			&i.DownloaderHost,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
