// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountRepositories(ctx context.Context) (int64, error)
	CountSkills(ctx context.Context) (int64, error)
	CountSkillsByRepository(ctx context.Context, repositoryID int64) (int64, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) error
	CreateSkill(ctx context.Context, arg CreateSkillParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) error
	DeleteRepository(ctx context.Context, id int64) error
	DeleteSkill(ctx context.Context, id int64) error
	DeleteSkillsByRepository(ctx context.Context, repositoryID int64) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteTagsBySkillID(ctx context.Context, skillID int64) error
	GetCurrentVersion(ctx context.Context) (int64, error)
	GetDefaultRepository(ctx context.Context) (Repository, error)
	GetPopularTags(ctx context.Context, limit int64) ([]GetPopularTagsRow, error)
	GetRepositoryByID(ctx context.Context, id int64) (Repository, error)
	GetRepositoryByName(ctx context.Context, name string) (Repository, error)
	GetSkillByID(ctx context.Context, id int64) (Skill, error)
	GetSkillByRepositoryAndSlug(ctx context.Context, arg GetSkillByRepositoryAndSlugParams) (Skill, error)
	GetTagsBySkillID(ctx context.Context, skillID int64) ([]Tag, error)
	GetVersionByNumber(ctx context.Context, version int64) (DbVersion, error)
	InsertVersion(ctx context.Context, arg InsertVersionParams) error
	ListAllRepositories(ctx context.Context) ([]Repository, error)
	ListAllSkills(ctx context.Context) ([]Skill, error)
	ListAllVersions(ctx context.Context) ([]DbVersion, error)
	ListRepositoriesByStatus(ctx context.Context, syncStatus sql.NullString) ([]Repository, error)
	ListSkillsByRepository(ctx context.Context, repositoryID int64) ([]Skill, error)
	SearchSkillsByAuthor(ctx context.Context, author sql.NullString) ([]Skill, error)
	SearchSkillsByCategory(ctx context.Context, category sql.NullString) ([]Skill, error)
	SearchSkillsByName(ctx context.Context, name string) ([]Skill, error)
	SearchSkillsByTag(ctx context.Context, tag string) ([]Skill, error)
	SetRepositoryAsDefault(ctx context.Context) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateRepositoryDefault(ctx context.Context, arg UpdateRepositoryDefaultParams) error
	UpdateRepositorySyncStatus(ctx context.Context, arg UpdateRepositorySyncStatusParams) error
	UpdateRepositoryURL(ctx context.Context, arg UpdateRepositoryURLParams) error
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) error
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) error
}

var _ Querier = (*Queries)(nil)
