// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package db

import (
	"context"
	"database/sql"
)

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*) as count FROM repositories
`

func (q *Queries) CountRepositories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepositories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepository = `-- name: CreateRepository :exec
INSERT INTO repositories (name, url, description, is_default, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRepositoryParams struct {
	Name        string         `json:"name"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	IsDefault   int64          `json:"is_default"`
	Priority    int64          `json:"priority"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, createRepository,
		arg.Name,
		arg.Url,
		arg.Description,
		arg.IsDefault,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories
WHERE id = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepository, id)
	return err
}

const getDefaultRepository = `-- name: GetDefaultRepository :one
SELECT id, name, url, description, is_default, priority, created_at, updated_at, last_synced_at, sync_status, sync_error FROM repositories
WHERE is_default = 1
LIMIT 1
`

func (q *Queries) GetDefaultRepository(ctx context.Context) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getDefaultRepository)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Description,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.SyncStatus,
		&i.SyncError,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, name, url, description, is_default, priority, created_at, updated_at, last_synced_at, sync_status, sync_error FROM repositories
WHERE id = ?
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Description,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.SyncStatus,
		&i.SyncError,
	)
	return i, err
}

const getRepositoryByName = `-- name: GetRepositoryByName :one
SELECT id, name, url, description, is_default, priority, created_at, updated_at, last_synced_at, sync_status, sync_error FROM repositories
WHERE name = ?
`

func (q *Queries) GetRepositoryByName(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByName, name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Description,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.SyncStatus,
		&i.SyncError,
	)
	return i, err
}

const listAllRepositories = `-- name: ListAllRepositories :many
SELECT id, name, url, description, is_default, priority, created_at, updated_at, last_synced_at, sync_status, sync_error FROM repositories
ORDER BY priority DESC, created_at ASC
`

func (q *Queries) ListAllRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Description,
			&i.IsDefault,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncedAt,
			&i.SyncStatus,
			&i.SyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByStatus = `-- name: ListRepositoriesByStatus :many
SELECT id, name, url, description, is_default, priority, created_at, updated_at, last_synced_at, sync_status, sync_error FROM repositories
WHERE sync_status = ?
ORDER BY priority DESC, created_at ASC
`

func (q *Queries) ListRepositoriesByStatus(ctx context.Context, syncStatus sql.NullString) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoriesByStatus, syncStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Description,
			&i.IsDefault,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncedAt,
			&i.SyncStatus,
			&i.SyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryAsDefault = `-- name: SetRepositoryAsDefault :exec
UPDATE repositories
SET is_default = 0
`

func (q *Queries) SetRepositoryAsDefault(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setRepositoryAsDefault)
	return err
}

const updateRepository = `-- name: UpdateRepository :exec
UPDATE repositories
SET url = ?, description = ?, priority = ?, updated_at = ?
WHERE id = ?
`

type UpdateRepositoryParams struct {
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	Priority    int64          `json:"priority"`
	UpdatedAt   string         `json:"updated_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, updateRepository,
		arg.Url,
		arg.Description,
		arg.Priority,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateRepositoryDefault = `-- name: UpdateRepositoryDefault :exec
UPDATE repositories
SET is_default = 1, updated_at = ?
WHERE id = ?
`

type UpdateRepositoryDefaultParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateRepositoryDefault(ctx context.Context, arg UpdateRepositoryDefaultParams) error {
	_, err := q.db.ExecContext(ctx, updateRepositoryDefault, arg.UpdatedAt, arg.ID)
	return err
}

const updateRepositorySyncStatus = `-- name: UpdateRepositorySyncStatus :exec
UPDATE repositories
SET sync_status = ?, last_synced_at = ?, sync_error = ?, updated_at = ?
WHERE id = ?
`

type UpdateRepositorySyncStatusParams struct {
	SyncStatus   sql.NullString `json:"sync_status"`
	LastSyncedAt sql.NullString `json:"last_synced_at"`
	SyncError    sql.NullString `json:"sync_error"`
	UpdatedAt    string         `json:"updated_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateRepositorySyncStatus(ctx context.Context, arg UpdateRepositorySyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRepositorySyncStatus,
		arg.SyncStatus,
		arg.LastSyncedAt,
		arg.SyncError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateRepositoryURL = `-- name: UpdateRepositoryURL :exec
UPDATE repositories
SET url = ?, updated_at = ?
WHERE id = ?
`

type UpdateRepositoryURLParams struct {
	Url       string `json:"url"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateRepositoryURL(ctx context.Context, arg UpdateRepositoryURLParams) error {
	_, err := q.db.ExecContext(ctx, updateRepositoryURL, arg.Url, arg.UpdatedAt, arg.ID)
	return err
}
