// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DbVersion struct {
	Version     int64          `json:"version"`
	AppliedAt   string         `json:"applied_at"`
	Description sql.NullString `json:"description"`
}

type Repository struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Url          string         `json:"url"`
	Description  sql.NullString `json:"description"`
	IsDefault    int64          `json:"is_default"`
	Priority     int64          `json:"priority"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	LastSyncedAt sql.NullString `json:"last_synced_at"`
	SyncStatus   sql.NullString `json:"sync_status"`
	SyncError    sql.NullString `json:"sync_error"`
}

type Skill struct {
	ID             int64          `json:"id"`
	RepositoryID   int64          `json:"repository_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    sql.NullString `json:"description"`
	Version        sql.NullString `json:"version"`
	Author         sql.NullString `json:"author"`
	RepoUrl        sql.NullString `json:"repo_url"`
	RepoOwner      sql.NullString `json:"repo_owner"`
	RepoName       sql.NullString `json:"repo_name"`
	Stars          sql.NullInt64  `json:"stars"`
	Forks          sql.NullInt64  `json:"forks"`
	Downloads      sql.NullInt64  `json:"downloads"`
	Language       sql.NullString `json:"language"`
	License        sql.NullString `json:"license"`
	Homepage       sql.NullString `json:"homepage"`
	Category       sql.NullString `json:"category"`
	SecurityStatus sql.NullString `json:"security_status"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	IndexedAt      string         `json:"indexed_at"`
}

type Tag struct {
	ID      int64  `json:"id"`
	SkillID int64  `json:"skill_id"`
	Tag     string `json:"tag"`
}
