// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package db

import (
	"context"
	"database/sql"
)

const countSkills = `-- name: CountSkills :one
SELECT COUNT(*) as count FROM skills
`

func (q *Queries) CountSkills(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSkillsByRepository = `-- name: CountSkillsByRepository :one
SELECT COUNT(*) as count FROM skills WHERE repository_id = ?
`

func (q *Queries) CountSkillsByRepository(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkillsByRepository, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skills (
    repository_id, name, slug, description, version, author, 
    repo_url, repo_owner, repo_name, stars, forks, downloads, 
    language, license, homepage, category, security_status, 
    created_at, updated_at, indexed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillParams struct {
	RepositoryID   int64          `json:"repository_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    sql.NullString `json:"description"`
	Version        sql.NullString `json:"version"`
	Author         sql.NullString `json:"author"`
	RepoUrl        sql.NullString `json:"repo_url"`
	RepoOwner      sql.NullString `json:"repo_owner"`
	RepoName       sql.NullString `json:"repo_name"`
	Stars          sql.NullInt64  `json:"stars"`
	Forks          sql.NullInt64  `json:"forks"`
	Downloads      sql.NullInt64  `json:"downloads"`
	Language       sql.NullString `json:"language"`
	License        sql.NullString `json:"license"`
	Homepage       sql.NullString `json:"homepage"`
	Category       sql.NullString `json:"category"`
	SecurityStatus sql.NullString `json:"security_status"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	IndexedAt      string         `json:"indexed_at"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) error {
	_, err := q.db.ExecContext(ctx, createSkill,
		arg.RepositoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Version,
		arg.Author,
		arg.RepoUrl,
		arg.RepoOwner,
		arg.RepoName,
		arg.Stars,
		arg.Forks,
		arg.Downloads,
		arg.Language,
		arg.License,
		arg.Homepage,
		arg.Category,
		arg.SecurityStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IndexedAt,
	)
	return err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = ?
`

func (q *Queries) DeleteSkill(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, id)
	return err
}

const deleteSkillsByRepository = `-- name: DeleteSkillsByRepository :exec
DELETE FROM skills WHERE repository_id = ?
`

func (q *Queries) DeleteSkillsByRepository(ctx context.Context, repositoryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSkillsByRepository, repositoryID)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills WHERE id = ?
`

func (q *Queries) GetSkillByID(ctx context.Context, id int64) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.RepoUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.Stars,
		&i.Forks,
		&i.Downloads,
		&i.Language,
		&i.License,
		&i.Homepage,
		&i.Category,
		&i.SecurityStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexedAt,
	)
	return i, err
}

const getSkillByRepositoryAndSlug = `-- name: GetSkillByRepositoryAndSlug :one
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
WHERE repository_id = ? AND slug = ?
`

type GetSkillByRepositoryAndSlugParams struct {
	RepositoryID int64  `json:"repository_id"`
	Slug         string `json:"slug"`
}

func (q *Queries) GetSkillByRepositoryAndSlug(ctx context.Context, arg GetSkillByRepositoryAndSlugParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByRepositoryAndSlug, arg.RepositoryID, arg.Slug)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Version,
		&i.Author,
		&i.RepoUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.Stars,
		&i.Forks,
		&i.Downloads,
		&i.Language,
		&i.License,
		&i.Homepage,
		&i.Category,
		&i.SecurityStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexedAt,
	)
	return i, err
}

const listAllSkills = `-- name: ListAllSkills :many
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
ORDER BY repository_id, name ASC
`

func (q *Queries) ListAllSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByRepository = `-- name: ListSkillsByRepository :many
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
WHERE repository_id = ?
ORDER BY name ASC
`

func (q *Queries) ListSkillsByRepository(ctx context.Context, repositoryID int64) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByAuthor = `-- name: SearchSkillsByAuthor :many
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
WHERE author LIKE ?
ORDER BY name ASC
`

func (q *Queries) SearchSkillsByAuthor(ctx context.Context, author sql.NullString) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, searchSkillsByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByCategory = `-- name: SearchSkillsByCategory :many
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
WHERE category = ?
ORDER BY name ASC
`

func (q *Queries) SearchSkillsByCategory(ctx context.Context, category sql.NullString) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, searchSkillsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByName = `-- name: SearchSkillsByName :many
SELECT id, repository_id, name, slug, description, version, author, repo_url, repo_owner, repo_name, stars, forks, downloads, language, license, homepage, category, security_status, created_at, updated_at, indexed_at FROM skills
WHERE name LIKE ?
ORDER BY name ASC
`

func (q *Queries) SearchSkillsByName(ctx context.Context, name string) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, searchSkillsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skills
SET description = ?, version = ?, author = ?, repo_url = ?, 
    repo_owner = ?, repo_name = ?, stars = ?, forks = ?, downloads = ?, 
    language = ?, license = ?, homepage = ?, category = ?, 
    security_status = ?, updated_at = ?
WHERE id = ?
`

type UpdateSkillParams struct {
	Description    sql.NullString `json:"description"`
	Version        sql.NullString `json:"version"`
	Author         sql.NullString `json:"author"`
	RepoUrl        sql.NullString `json:"repo_url"`
	RepoOwner      sql.NullString `json:"repo_owner"`
	RepoName       sql.NullString `json:"repo_name"`
	Stars          sql.NullInt64  `json:"stars"`
	Forks          sql.NullInt64  `json:"forks"`
	Downloads      sql.NullInt64  `json:"downloads"`
	Language       sql.NullString `json:"language"`
	License        sql.NullString `json:"license"`
	Homepage       sql.NullString `json:"homepage"`
	Category       sql.NullString `json:"category"`
	SecurityStatus sql.NullString `json:"security_status"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.ExecContext(ctx, updateSkill,
		arg.Description,
		arg.Version,
		arg.Author,
		arg.RepoUrl,
		arg.RepoOwner,
		arg.RepoName,
		arg.Stars,
		arg.Forks,
		arg.Downloads,
		arg.Language,
		arg.License,
		arg.Homepage,
		arg.Category,
		arg.SecurityStatus,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertSkill = `-- name: UpsertSkill :exec
INSERT OR REPLACE INTO skills (
    id, repository_id, name, slug, description, version, author,
    repo_url, repo_owner, repo_name, stars, forks, downloads,
    language, license, homepage, category, security_status,
    created_at, updated_at, indexed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertSkillParams struct {
	ID             int64          `json:"id"`
	RepositoryID   int64          `json:"repository_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    sql.NullString `json:"description"`
	Version        sql.NullString `json:"version"`
	Author         sql.NullString `json:"author"`
	RepoUrl        sql.NullString `json:"repo_url"`
	RepoOwner      sql.NullString `json:"repo_owner"`
	RepoName       sql.NullString `json:"repo_name"`
	Stars          sql.NullInt64  `json:"stars"`
	Forks          sql.NullInt64  `json:"forks"`
	Downloads      sql.NullInt64  `json:"downloads"`
	Language       sql.NullString `json:"language"`
	License        sql.NullString `json:"license"`
	Homepage       sql.NullString `json:"homepage"`
	Category       sql.NullString `json:"category"`
	SecurityStatus sql.NullString `json:"security_status"`
	CreatedAt      sql.NullString `json:"created_at"`
	UpdatedAt      sql.NullString `json:"updated_at"`
	IndexedAt      string         `json:"indexed_at"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkill,
		arg.ID,
		arg.RepositoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Version,
		arg.Author,
		arg.RepoUrl,
		arg.RepoOwner,
		arg.RepoName,
		arg.Stars,
		arg.Forks,
		arg.Downloads,
		arg.Language,
		arg.License,
		arg.Homepage,
		arg.Category,
		arg.SecurityStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IndexedAt,
	)
	return err
}
