// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :exec
INSERT INTO tags (skill_id, tag) VALUES (?, ?)
`

type CreateTagParams struct {
	SkillID int64  `json:"skill_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.ExecContext(ctx, createTag, arg.SkillID, arg.Tag)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE skill_id = ? AND tag = ?
`

type DeleteTagParams struct {
	SkillID int64  `json:"skill_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.SkillID, arg.Tag)
	return err
}

const deleteTagsBySkillID = `-- name: DeleteTagsBySkillID :exec
DELETE FROM tags WHERE skill_id = ?
`

func (q *Queries) DeleteTagsBySkillID(ctx context.Context, skillID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagsBySkillID, skillID)
	return err
}

const getPopularTags = `-- name: GetPopularTags :many
SELECT tag, COUNT(*) as count 
FROM tags 
GROUP BY tag 
ORDER BY count DESC 
LIMIT ?
`

type GetPopularTagsRow struct {
	Tag   string `json:"tag"`
	Count int64  `json:"count"`
}

func (q *Queries) GetPopularTags(ctx context.Context, limit int64) ([]GetPopularTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularTagsRow
	for rows.Next() {
		var i GetPopularTagsRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsBySkillID = `-- name: GetTagsBySkillID :many
SELECT id, skill_id, tag FROM tags WHERE skill_id = ?
`

func (q *Queries) GetTagsBySkillID(ctx context.Context, skillID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsBySkillID, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.SkillID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByTag = `-- name: SearchSkillsByTag :many
SELECT DISTINCT s.id, s.repository_id, s.name, s.slug, s.description, s.version, s.author, s.repo_url, s.repo_owner, s.repo_name, s.stars, s.forks, s.downloads, s.language, s.license, s.homepage, s.category, s.security_status, s.created_at, s.updated_at, s.indexed_at FROM skills s
INNER JOIN tags t ON s.id = t.skill_id
WHERE t.tag = ?
ORDER BY s.name ASC
`

func (q *Queries) SearchSkillsByTag(ctx context.Context, tag string) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, searchSkillsByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Version,
			&i.Author,
			&i.RepoUrl,
			&i.RepoOwner,
			&i.RepoName,
			&i.Stars,
			&i.Forks,
			&i.Downloads,
			&i.Language,
			&i.License,
			&i.Homepage,
			&i.Category,
			&i.SecurityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
