// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: version.sql

package db

import (
	"context"
	"database/sql"
)

const getCurrentVersion = `-- name: GetCurrentVersion :one
SELECT version FROM db_version
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetCurrentVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getVersionByNumber = `-- name: GetVersionByNumber :one
SELECT version, applied_at, description FROM db_version WHERE version = ?
`

func (q *Queries) GetVersionByNumber(ctx context.Context, version int64) (DbVersion, error) {
	row := q.db.QueryRowContext(ctx, getVersionByNumber, version)
	var i DbVersion
	err := row.Scan(&i.Version, &i.AppliedAt, &i.Description)
	return i, err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO db_version (version, applied_at, description)
VALUES (?, ?, ?)
`

type InsertVersionParams struct {
	Version     int64          `json:"version"`
	AppliedAt   string         `json:"applied_at"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertVersion, arg.Version, arg.AppliedAt, arg.Description)
	return err
}

const listAllVersions = `-- name: ListAllVersions :many
SELECT version, applied_at, description FROM db_version ORDER BY version ASC
`

func (q *Queries) ListAllVersions(ctx context.Context) ([]DbVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAllVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DbVersion
	for rows.Next() {
		var i DbVersion
		if err := rows.Scan(&i.Version, &i.AppliedAt, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
